pipeline{
    agent any
    tools{
        maven 'M2_HOME'
    }
    stages{
        stage(sonar-scan){
            steps{
                sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Guilenedeveops_geolocation190524'
            }
        }
        stage("maven"){
            steps{
             sh 'mvn clean 
             sh 'mvn validate'
             sh 'mvn compile'
             sh 'mvn install'
             sh 'mvn test'
             sh 'mvn package'
            }          
        }
        stage('upload artifact'){
            steps{
                sh 'curl -uadmin:AP7bxAPKkWrSXTi9tv2SeCxA3Wn -T\
                target/bio*.jar \
                "http://ec2-100-26-10-142.compute-1.amazonaws.com:8081/artifactory/geolocation-new/geo/bio_${BUILD_ID}.jar"'


 }
        }

    }
}
  
  
