pipeline{
    agent any
    tools{
        maven 'M2_HOME'
    }
    stages{
        stage("sonar-scan"){
            steps{
                withSonarQubeEnv('sonarQube'){
                sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Guilenedeveops_geo-app'
                }
                
              }
        }
        stage("maven"){
            steps{
             sh 'mvn clean'
             sh 'mvn validate'
             sh 'mvn compile'
             sh 'mvn install'
             sh 'mvn test'
             sh 'mvn package'
            }          
        }
        stage('upload artifact'){
            steps{
                sh 'curl -uadmin:AP7bxAPKkWrSXTi9tv2SeCxA3Wn -T \
                 target/bio*.jar \ 
                 "http://54.164.53.36:8081/artifactory/study-app-geo/bio_${BUILD_ID}.jar"'


 

        }

    }
    }
}
  
  
